availability_zone = "eu-west-2a"           # Replace with a valid Availability_zone
ami               = "ami-07c1b39b7b3d2525d" # Replace with a valid AMI ID
tags              = "linux-server"               # Specify your tag's
region            = "eu-west-2"      # Replace the region with your own Region
volume_size       = "10"                     # Specify the Volume Size
instance_type     = "t2.micro"               # Specify the instance type
key_name          = "private"            # specify your desired key
text1             = "locals-example"
my_security_group = "my-security-group" # Please specify your security group by changing your own security group name
my_vpc            = "vpc-1"
AWS_ACCESS_KEY_ID     = 
AWS_SECRET_ACCESS_KEY = 
//instance_count     = 2
